server:
  port: 8002

spring:
  application:
    name: provider
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: provider
        heartbeat:
          enabled: true
        instanceZone: A
        catalog-services-watch:
          enabled: false