server:
  port: 28020

spring:
  application:
    name: dubbo-2-5-consumer

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  endpoint:
    health:
      probes:
        enabled: true